/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    subcategories: Subcategory;
    tags: Tag;
    resources: Resource;
    'resource-sources': ResourceSource;
    'resource-discovery-queue': ResourceDiscoveryQueue;
    documents: Document;
    'document-sections': DocumentSection;
    'code-examples': CodeExample;
    'difficulty-levels': DifficultyLevel;
    'programming-languages': ProgrammingLanguage;
    'edit-suggestions': EditSuggestion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'resource-sources': ResourceSourcesSelect<false> | ResourceSourcesSelect<true>;
    'resource-discovery-queue': ResourceDiscoveryQueueSelect<false> | ResourceDiscoveryQueueSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'document-sections': DocumentSectionsSelect<false> | DocumentSectionsSelect<true>;
    'code-examples': CodeExamplesSelect<false> | CodeExamplesSelect<true>;
    'difficulty-levels': DifficultyLevelsSelect<false> | DifficultyLevelsSelect<true>;
    'programming-languages': ProgrammingLanguagesSelect<false> | ProgrammingLanguagesSelect<true>;
    'edit-suggestions': EditSuggestionsSelect<false> | EditSuggestionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'cross-link-settings': CrossLinkSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'cross-link-settings': CrossLinkSettingsSelect<false> | CrossLinkSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS users who manage content and moderate submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name for the admin panel
   */
  name: string;
  /**
   * Short biography or description
   */
  bio?: string | null;
  /**
   * User role determines access level
   */
  role: 'admin' | 'editor' | 'moderator' | 'beta_tester';
  /**
   * Inactive users cannot log in
   */
  isActive?: boolean | null;
  /**
   * Fine-grained permissions (for moderators)
   */
  permissions?: {
    /**
     * Can approve or reject user comments
     */
    canApproveComments?: boolean | null;
    /**
     * Can approve or reject edit suggestions
     */
    canApproveEdits?: boolean | null;
    /**
     * Can create, edit, and delete resources
     */
    canManageResources?: boolean | null;
    /**
     * Can view site analytics and reports
     */
    canViewAnalytics?: boolean | null;
  };
  /**
   * Last successful login
   */
  lastLoginAt?: string | null;
  /**
   * Total number of logins
   */
  loginCount?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Uploaded images and files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility (required)
   */
  alt: string;
  /**
   * Optional caption for the image
   */
  caption?: string | null;
  /**
   * Category for organization
   */
  category?: ('avatar' | 'resource' | 'doc' | 'general') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * URL-friendly identifier (e.g., "mcp-servers")
   */
  slug: string;
  /**
   * Full display name (e.g., "MCP Servers")
   */
  name: string;
  /**
   * Abbreviated name for compact displays (e.g., "MCP")
   */
  shortName: string;
  description: string;
  /**
   * Emoji icon for the category (e.g., "🔌")
   */
  icon: string;
  color: 'violet' | 'blue' | 'cyan' | 'green' | 'yellow' | 'purple' | 'pink' | 'indigo' | 'amber' | 'rose';
  /**
   * Order for displaying categories (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subcategories belong to a parent category for hierarchical organization
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  /**
   * Display name (e.g., "Desktop Apps", "CLI Tools")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "desktop-apps")
   */
  slug: string;
  /**
   * Parent category this subcategory belongs to
   */
  category: number | Category;
  /**
   * Brief description of what resources belong here
   */
  description?: string | null;
  /**
   * Optional emoji icon for the subcategory
   */
  icon?: string | null;
  /**
   * Number of resources in this subcategory (auto-calculated)
   */
  resourceCount?: number | null;
  /**
   * Display order within the parent category (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Tag name (e.g., "typescript", "ai-agent")
   */
  name: string;
  /**
   * Optional description of what this tag represents
   */
  description?: string | null;
  /**
   * Number of resources using this tag (auto-calculated)
   */
  resourceCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * Publication workflow status
   */
  publishStatus: 'published' | 'hidden' | 'pending_review' | 'rejected' | 'draft';
  /**
   * Resource title (e.g., "Claude Desktop")
   */
  title: string;
  /**
   * Brief description of the resource
   */
  description: string;
  /**
   * Primary URL for the resource
   */
  url: string;
  /**
   * Primary category for this resource
   */
  category: number | Category;
  /**
   * Subcategory within the parent category
   */
  subcategory?: (number | null) | Subcategory;
  /**
   * Tags for filtering and discovery
   */
  tags?: (number | Tag)[] | null;
  /**
   * Skill level required to use this resource
   */
  difficulty?: (number | null) | DifficultyLevel;
  status: 'official' | 'community' | 'beta' | 'deprecated' | 'archived';
  /**
   * GitHub repository information (if applicable)
   */
  github?: {
    /**
     * GitHub username or organization
     */
    owner?: string | null;
    /**
     * Repository name
     */
    repo?: string | null;
    /**
     * Star count (auto-updated or manual)
     */
    stars?: number | null;
    forks?: number | null;
    /**
     * Last commit date
     */
    lastUpdated?: string | null;
    /**
     * Primary programming language
     */
    language?: (number | null) | ProgrammingLanguage;
  };
  /**
   * Latest version (for packages, MCP servers)
   */
  version?: string | null;
  /**
   * Package namespace (e.g., "@modelcontextprotocol")
   */
  namespace?: string | null;
  /**
   * Show on homepage featured section
   */
  featured?: boolean | null;
  /**
   * Reason for featuring (shown as badge)
   */
  featuredReason?: ('editors-pick' | 'most-popular' | 'new' | 'trending' | 'essential') | null;
  /**
   * Date this resource was added to the collection
   */
  addedDate: string;
  /**
   * Last date this resource was verified as active
   */
  lastVerified: string;
  /**
   * Link this resource to related documentation
   */
  crossLinking?: {
    /**
     * Documentation pages related to this resource
     */
    relatedDocs?: (number | Document)[] | null;
    /**
     * Specific sections related to this resource
     */
    relatedSections?: (number | DocumentSection)[] | null;
    /**
     * Auto-matched documents based on shared tags (read-only)
     */
    autoMatchedDocs?: (number | Document)[] | null;
  };
  /**
   * Metadata about how this resource was discovered
   */
  discovery?: {
    /**
     * The source from which this resource was discovered
     */
    source?: (number | null) | ResourceSource;
    /**
     * When this resource was discovered
     */
    discoveredAt?: string | null;
    /**
     * How this resource was added to the system
     */
    discoveredBy?: ('ai' | 'manual' | 'import' | 'suggestion') | null;
    /**
     * AI confidence score (0-100) for auto-discovered resources
     */
    aiConfidenceScore?: number | null;
    /**
     * AI analysis notes and reasoning
     */
    aiNotes?: string | null;
  };
  /**
   * Review and approval tracking
   */
  review?: {
    /**
     * Admin who reviewed this resource
     */
    reviewedBy?: (number | null) | User;
    /**
     * When this resource was last reviewed
     */
    reviewedAt?: string | null;
    /**
     * Notes from the reviewer
     */
    reviewNotes?: string | null;
    /**
     * Reason for rejection (if applicable)
     */
    rejectionReason?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Skill levels for classifying resource difficulty
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulty-levels".
 */
export interface DifficultyLevel {
  id: number;
  /**
   * Display name (e.g., "Beginner", "Expert")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "beginner", "expert")
   */
  slug: string;
  /**
   * What this level means (e.g., "No prior experience needed")
   */
  description?: string | null;
  /**
   * Badge color for this difficulty level
   */
  color: 'green' | 'blue' | 'yellow' | 'orange' | 'red' | 'purple' | 'gray';
  /**
   * Optional emoji icon (e.g., "🌱", "🔥")
   */
  icon?: string | null;
  /**
   * Display order (0=easiest, higher=harder)
   */
  sortOrder: number;
  /**
   * Number of resources at this level (auto-calculated)
   */
  resourceCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Programming languages used in resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programming-languages".
 */
export interface ProgrammingLanguage {
  id: number;
  /**
   * Display name (e.g., "TypeScript", "Python")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "typescript", "python")
   */
  slug: string;
  /**
   * Alternative names that should map to this language
   */
  aliases?:
    | {
        /**
         * Alternative name (e.g., "JS" for JavaScript)
         */
        alias?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tailwind color class for badges (e.g., "blue-600", "yellow-500")
   */
  color: string;
  /**
   * Optional emoji or icon identifier
   */
  icon?: string | null;
  /**
   * Official language website URL
   */
  website?: string | null;
  /**
   * Number of resources using this language (auto-calculated)
   */
  resourceCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documentation pages synced from MDX files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * URL path slug (e.g., "getting-started/installation")
   */
  slug: string;
  /**
   * Document title from frontmatter
   */
  title: string;
  /**
   * Document description from frontmatter
   */
  description?: string | null;
  /**
   * Documentation category (e.g., "getting-started", "api")
   */
  docCategory: string;
  /**
   * Tags for auto-matching with resources
   */
  tags?: (number | Tag)[] | null;
  /**
   * How to display related resources
   */
  displayMode?: ('hover' | 'cards' | 'both') | null;
  /**
   * Enable automatic tag-based matching
   */
  autoMatchEnabled?: boolean | null;
  /**
   * Manually linked resources (takes priority over auto-matched)
   */
  relatedResources?: (number | Resource)[] | null;
  /**
   * Resources to exclude from auto-matching
   */
  excludedResources?: (number | Resource)[] | null;
  /**
   * Automatically matched based on shared tags (read-only)
   */
  autoMatchedResources?: (number | Resource)[] | null;
  /**
   * Sync tracking information
   */
  syncInfo?: {
    /**
     * Path to source MDX file
     */
    mdxPath?: string | null;
    /**
     * MD5 hash for change detection
     */
    contentHash?: string | null;
    /**
     * Last sync timestamp
     */
    lastSynced?: string | null;
  };
  /**
   * Additional metadata
   */
  metadata?: {
    /**
     * Estimated reading time
     */
    readingTime?: string | null;
    /**
     * Word count
     */
    wordCount?: number | null;
    /**
     * Number of headings/sections
     */
    headingCount?: number | null;
    /**
     * Number of code blocks
     */
    codeBlockCount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Document sections for granular cross-linking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-sections".
 */
export interface DocumentSection {
  id: number;
  /**
   * Parent document this section belongs to
   */
  document: number | Document;
  /**
   * Anchor ID (e.g., "installation-methods")
   */
  headingId: string;
  /**
   * Heading text content
   */
  headingText: string;
  /**
   * Heading level (1-6)
   */
  headingLevel: number;
  /**
   * Position in document
   */
  order: number;
  /**
   * Section-specific tags for targeted matching
   */
  tags?: (number | Tag)[] | null;
  /**
   * Resources specifically related to this section
   */
  relatedResources?: (number | Resource)[] | null;
  /**
   * Show resources after this section
   */
  showRelatedResources?: boolean | null;
  /**
   * Display mode override
   */
  displayMode?: ('inherit' | 'hover' | 'cards') | null;
  /**
   * Preview of section content (first 200 chars)
   */
  contentPreview?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sources for discovering new resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-sources".
 */
export interface ResourceSource {
  id: number;
  /**
   * Display name for this source (e.g., "Awesome Claude Code")
   */
  name: string;
  /**
   * What kind of resources can be found from this source
   */
  description?: string | null;
  /**
   * Type of source determines how discovery works
   */
  type: 'github_repo' | 'github_search' | 'awesome_list' | 'npm' | 'pypi' | 'website' | 'rss' | 'api' | 'manual';
  /**
   * Primary URL or API endpoint for this source
   */
  url: string;
  /**
   * GitHub-specific configuration
   */
  github?: {
    /**
     * Repository owner (username or organization)
     */
    owner?: string | null;
    /**
     * Repository name
     */
    repo?: string | null;
    /**
     * Branch to scan (default: main)
     */
    branch?: string | null;
    /**
     * Path to scan (e.g., "README.md" or "docs/")
     */
    path?: string | null;
    /**
     * GitHub search query (for github_search type)
     */
    searchQuery?: string | null;
    /**
     * Comma-separated topics to filter by
     */
    topics?: string | null;
  };
  /**
   * Package registry configuration
   */
  registry?: {
    /**
     * Package search query (e.g., "claude", "anthropic")
     */
    searchQuery?: string | null;
    /**
     * Package scope to monitor (e.g., "@anthropic-ai")
     */
    scope?: string | null;
    /**
     * Comma-separated keywords to filter by
     */
    keywords?: string | null;
  };
  /**
   * How discovered resources should be processed
   */
  discoverySettings?: {
    /**
     * Default category for resources from this source
     */
    defaultCategory?: (number | null) | Category;
    /**
     * Default subcategory for resources from this source
     */
    defaultSubcategory?: (number | null) | Subcategory;
    /**
     * Tags to automatically apply to discovered resources
     */
    defaultTags?: (number | Tag)[] | null;
    /**
     * Automatically approve resources from trusted sources
     */
    autoApprove?: boolean | null;
    /**
     * Minimum GitHub stars required (0 = no minimum)
     */
    minStars?: number | null;
    /**
     * Minimum weekly downloads required (0 = no minimum)
     */
    minDownloads?: number | null;
    /**
     * URL patterns to include (one per line, regex supported)
     */
    includePatterns?: string | null;
    /**
     * URL patterns to exclude (one per line, regex supported)
     */
    excludePatterns?: string | null;
  };
  /**
   * Enable or disable this source
   */
  isActive?: boolean | null;
  /**
   * How often to scan this source
   */
  scanFrequency?: ('daily' | 'weekly' | 'monthly' | 'manual') | null;
  /**
   * Last successful scan timestamp
   */
  lastScannedAt?: string | null;
  /**
   * Status of last scan
   */
  lastScanStatus?: ('success' | 'partial' | 'failed' | 'never') | null;
  /**
   * Error message from last failed scan
   */
  lastScanError?: string | null;
  /**
   * Total resources discovered from this source
   */
  resourceCount?: number | null;
  /**
   * Resources pending review from this source
   */
  pendingCount?: number | null;
  /**
   * Internal notes about this source
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-discovered resources pending review
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-discovery-queue".
 */
export interface ResourceDiscoveryQueue {
  id: number;
  /**
   * Resource title (AI-suggested, editable)
   */
  title: string;
  /**
   * Resource description (AI-suggested, editable)
   */
  description: string;
  /**
   * Primary URL for the resource
   */
  url: string;
  /**
   * AI-suggested category (can be changed)
   */
  suggestedCategory?: (number | null) | Category;
  /**
   * AI-suggested subcategory
   */
  suggestedSubcategory?: (number | null) | Subcategory;
  /**
   * AI-suggested tags
   */
  suggestedTags?: (number | Tag)[] | null;
  /**
   * AI-suggested difficulty level
   */
  suggestedDifficulty?: (number | null) | DifficultyLevel;
  /**
   * AI-suggested status
   */
  suggestedStatus?: ('official' | 'community' | 'beta' | 'deprecated') | null;
  /**
   * GitHub repository data
   */
  github?: {
    /**
     * Repository owner
     */
    owner?: string | null;
    /**
     * Repository name
     */
    repo?: string | null;
    /**
     * Star count
     */
    stars?: number | null;
    /**
     * Fork count
     */
    forks?: number | null;
    /**
     * Primary language
     */
    language?: string | null;
    /**
     * Last commit date
     */
    lastCommit?: string | null;
    /**
     * Open issues count
     */
    openIssues?: number | null;
    /**
     * Repository license
     */
    license?: string | null;
  };
  /**
   * Package registry data
   */
  package?: {
    /**
     * Package name
     */
    name?: string | null;
    /**
     * Latest version
     */
    version?: string | null;
    /**
     * Weekly downloads
     */
    weeklyDownloads?: number | null;
    /**
     * Package registry
     */
    registry?: ('npm' | 'pypi') | null;
  };
  /**
   * Source where this resource was discovered
   */
  source?: (number | null) | ResourceSource;
  /**
   * Specific URL where this was found
   */
  sourceUrl?: string | null;
  /**
   * Raw scraped data (for debugging)
   */
  rawData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Results from Claude Opus 4.5 analysis
   */
  aiAnalysis?: {
    /**
     * Overall confidence in categorization (0-100)
     */
    confidenceScore?: number | null;
    /**
     * Relevance to Claude/Anthropic ecosystem (0-100)
     */
    relevanceScore?: number | null;
    /**
     * Project quality assessment (0-100)
     */
    qualityScore?: number | null;
    /**
     * AI reasoning for categorization and scores
     */
    reasoning?: string | null;
    /**
     * Suggestions for improving the resource listing
     */
    suggestedImprovements?: string | null;
    /**
     * Potential issues or concerns noted by AI
     */
    warnings?: string | null;
    /**
     * When the AI analysis was performed
     */
    analyzedAt?: string | null;
  };
  /**
   * Review workflow status
   */
  status: 'pending' | 'approved' | 'rejected' | 'duplicate' | 'needs_info';
  /**
   * Review priority
   */
  priority?: ('high' | 'normal' | 'low') | null;
  /**
   * Admin who reviewed this item
   */
  reviewedBy?: (number | null) | User;
  /**
   * When this was reviewed
   */
  reviewedAt?: string | null;
  /**
   * Notes from the reviewer
   */
  reviewNotes?: string | null;
  /**
   * Reason for rejection
   */
  rejectionReason?: string | null;
  /**
   * Resource created from this queue item
   */
  createdResource?: (number | null) | Resource;
  /**
   * Existing resource this is a duplicate of
   */
  duplicateOf?: (number | null) | Resource;
  updatedAt: string;
  createdAt: string;
}
/**
 * Code blocks for targeted resource linking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-examples".
 */
export interface CodeExample {
  id: number;
  /**
   * Parent document containing this code block
   */
  document: number | Document;
  /**
   * Parent section (optional, for nested context)
   */
  section?: (number | null) | DocumentSection;
  /**
   * Unique identifier for this code block
   */
  codeId: string;
  /**
   * Optional title for the code block
   */
  title?: string | null;
  /**
   * Filename if specified (e.g., "settings.json")
   */
  filename?: string | null;
  /**
   * Programming language
   */
  language?: (number | null) | ProgrammingLanguage;
  /**
   * Position in document
   */
  order: number;
  /**
   * First 500 characters of the code
   */
  codePreview?: string | null;
  /**
   * Tags for this specific code example
   */
  tags?: (number | Tag)[] | null;
  /**
   * Resources related to this code example
   */
  relatedResources?: (number | Resource)[] | null;
  /**
   * Code block metadata
   */
  metadata?: {
    /**
     * Number of lines
     */
    lineCount?: number | null;
    /**
     * Detected patterns (cli, apiCall, config, etc.)
     */
    patterns?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * User-submitted edit suggestions for docs and resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edit-suggestions".
 */
export interface EditSuggestion {
  id: number;
  /**
   * Brief description of the suggested change
   */
  title: string;
  /**
   * Type of content being edited
   */
  targetType: 'doc' | 'resource';
  /**
   * ID or slug of the target content
   */
  targetId: string;
  /**
   * URL where the suggestion was made
   */
  targetUrl?: string | null;
  /**
   * The current content (for reference)
   */
  currentContent?: string | null;
  /**
   * The proposed changes (use markdown)
   */
  suggestedContent: string;
  /**
   * Why this change should be made
   */
  reason?: string | null;
  status: 'pending' | 'reviewing' | 'approved' | 'rejected' | 'merged';
  /**
   * Priority for review
   */
  priority?: ('low' | 'normal' | 'high' | 'critical') | null;
  /**
   * Information about who submitted this suggestion
   */
  submitter?: {
    type?: ('public' | 'cms' | 'anonymous') | null;
    /**
     * User ID (public or CMS)
     */
    userId?: string | null;
    /**
     * Email for notification about status
     */
    email?: string | null;
    /**
     * Display name
     */
    name?: string | null;
  };
  submitterEmail?: string | null;
  /**
   * Moderator who reviewed this
   */
  reviewedBy?: (number | null) | User;
  /**
   * Notes from the reviewer (internal)
   */
  reviewNotes?: string | null;
  /**
   * Reason for rejection (sent to submitter)
   */
  rejectionReason?: string | null;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'resource-sources';
        value: number | ResourceSource;
      } | null)
    | ({
        relationTo: 'resource-discovery-queue';
        value: number | ResourceDiscoveryQueue;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'document-sections';
        value: number | DocumentSection;
      } | null)
    | ({
        relationTo: 'code-examples';
        value: number | CodeExample;
      } | null)
    | ({
        relationTo: 'difficulty-levels';
        value: number | DifficultyLevel;
      } | null)
    | ({
        relationTo: 'programming-languages';
        value: number | ProgrammingLanguage;
      } | null)
    | ({
        relationTo: 'edit-suggestions';
        value: number | EditSuggestion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  role?: T;
  isActive?: T;
  permissions?:
    | T
    | {
        canApproveComments?: T;
        canApproveEdits?: T;
        canManageResources?: T;
        canViewAnalytics?: T;
      };
  lastLoginAt?: T;
  loginCount?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avatar?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortName?: T;
  description?: T;
  icon?: T;
  color?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  icon?: T;
  resourceCount?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  resourceCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  publishStatus?: T;
  title?: T;
  description?: T;
  url?: T;
  category?: T;
  subcategory?: T;
  tags?: T;
  difficulty?: T;
  status?: T;
  github?:
    | T
    | {
        owner?: T;
        repo?: T;
        stars?: T;
        forks?: T;
        lastUpdated?: T;
        language?: T;
      };
  version?: T;
  namespace?: T;
  featured?: T;
  featuredReason?: T;
  addedDate?: T;
  lastVerified?: T;
  crossLinking?:
    | T
    | {
        relatedDocs?: T;
        relatedSections?: T;
        autoMatchedDocs?: T;
      };
  discovery?:
    | T
    | {
        source?: T;
        discoveredAt?: T;
        discoveredBy?: T;
        aiConfidenceScore?: T;
        aiNotes?: T;
      };
  review?:
    | T
    | {
        reviewedBy?: T;
        reviewedAt?: T;
        reviewNotes?: T;
        rejectionReason?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-sources_select".
 */
export interface ResourceSourcesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  url?: T;
  github?:
    | T
    | {
        owner?: T;
        repo?: T;
        branch?: T;
        path?: T;
        searchQuery?: T;
        topics?: T;
      };
  registry?:
    | T
    | {
        searchQuery?: T;
        scope?: T;
        keywords?: T;
      };
  discoverySettings?:
    | T
    | {
        defaultCategory?: T;
        defaultSubcategory?: T;
        defaultTags?: T;
        autoApprove?: T;
        minStars?: T;
        minDownloads?: T;
        includePatterns?: T;
        excludePatterns?: T;
      };
  isActive?: T;
  scanFrequency?: T;
  lastScannedAt?: T;
  lastScanStatus?: T;
  lastScanError?: T;
  resourceCount?: T;
  pendingCount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-discovery-queue_select".
 */
export interface ResourceDiscoveryQueueSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  url?: T;
  suggestedCategory?: T;
  suggestedSubcategory?: T;
  suggestedTags?: T;
  suggestedDifficulty?: T;
  suggestedStatus?: T;
  github?:
    | T
    | {
        owner?: T;
        repo?: T;
        stars?: T;
        forks?: T;
        language?: T;
        lastCommit?: T;
        openIssues?: T;
        license?: T;
      };
  package?:
    | T
    | {
        name?: T;
        version?: T;
        weeklyDownloads?: T;
        registry?: T;
      };
  source?: T;
  sourceUrl?: T;
  rawData?: T;
  aiAnalysis?:
    | T
    | {
        confidenceScore?: T;
        relevanceScore?: T;
        qualityScore?: T;
        reasoning?: T;
        suggestedImprovements?: T;
        warnings?: T;
        analyzedAt?: T;
      };
  status?: T;
  priority?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  reviewNotes?: T;
  rejectionReason?: T;
  createdResource?: T;
  duplicateOf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  docCategory?: T;
  tags?: T;
  displayMode?: T;
  autoMatchEnabled?: T;
  relatedResources?: T;
  excludedResources?: T;
  autoMatchedResources?: T;
  syncInfo?:
    | T
    | {
        mdxPath?: T;
        contentHash?: T;
        lastSynced?: T;
      };
  metadata?:
    | T
    | {
        readingTime?: T;
        wordCount?: T;
        headingCount?: T;
        codeBlockCount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-sections_select".
 */
export interface DocumentSectionsSelect<T extends boolean = true> {
  document?: T;
  headingId?: T;
  headingText?: T;
  headingLevel?: T;
  order?: T;
  tags?: T;
  relatedResources?: T;
  showRelatedResources?: T;
  displayMode?: T;
  contentPreview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-examples_select".
 */
export interface CodeExamplesSelect<T extends boolean = true> {
  document?: T;
  section?: T;
  codeId?: T;
  title?: T;
  filename?: T;
  language?: T;
  order?: T;
  codePreview?: T;
  tags?: T;
  relatedResources?: T;
  metadata?:
    | T
    | {
        lineCount?: T;
        patterns?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulty-levels_select".
 */
export interface DifficultyLevelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  icon?: T;
  sortOrder?: T;
  resourceCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programming-languages_select".
 */
export interface ProgrammingLanguagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  color?: T;
  icon?: T;
  website?: T;
  resourceCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edit-suggestions_select".
 */
export interface EditSuggestionsSelect<T extends boolean = true> {
  title?: T;
  targetType?: T;
  targetId?: T;
  targetUrl?: T;
  currentContent?: T;
  suggestedContent?: T;
  reason?: T;
  status?: T;
  priority?: T;
  submitter?:
    | T
    | {
        type?: T;
        userId?: T;
        email?: T;
        name?: T;
      };
  submitterEmail?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  rejectionReason?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site configuration - changes apply site-wide
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  general: {
    /**
     * The name of the website
     */
    siteName: string;
    /**
     * Short tagline displayed in header and meta tags
     */
    tagline: string;
    /**
     * Used for SEO meta description and Open Graph
     */
    description: string;
    /**
     * Current version displayed in footer
     */
    version?: string | null;
  };
  social?: {
    /**
     * GitHub repository URL
     */
    github?: string | null;
    /**
     * Twitter/X profile URL (optional)
     */
    twitter?: string | null;
    /**
     * Discord server invite URL (optional)
     */
    discord?: string | null;
    /**
     * LinkedIn profile or company page URL (optional)
     */
    linkedin?: string | null;
  };
  footer?: {
    /**
     * Copyright notice in footer
     */
    copyrightText?: string | null;
    showVersion?: boolean | null;
    /**
     * Shows build date and commit SHA
     */
    showBuildInfo?: boolean | null;
  };
  seo?: {
    /**
     * Default Open Graph image for social sharing
     */
    ogImage?: string | null;
    /**
     * Twitter handle for Twitter Cards (e.g., @claudeinsider)
     */
    twitterHandle?: string | null;
    /**
     * Google Analytics measurement ID (optional)
     */
    googleAnalyticsId?: string | null;
  };
  features?: {
    /**
     * Enable to show maintenance page to visitors
     */
    maintenanceMode?: boolean | null;
    /**
     * Message displayed during maintenance
     */
    maintenanceMessage?: string | null;
    /**
     * Show/hide the AI voice assistant feature
     */
    enableVoiceAssistant?: boolean | null;
    /**
     * Enable/disable the search functionality
     */
    enableSearch?: boolean | null;
    /**
     * Enable Vercel Analytics tracking
     */
    enableAnalytics?: boolean | null;
  };
  contact?: {
    /**
     * Primary contact email address
     */
    email?: string | null;
    /**
     * URL for support/issues
     */
    supportUrl?: string | null;
  };
  announcement?: {
    enabled?: boolean | null;
    /**
     * Short message for the top banner
     */
    message?: string | null;
    /**
     * Optional link for "Learn more"
     */
    link?: string | null;
    type?: ('info' | 'success' | 'warning' | 'feature') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure cross-linking between documentation and resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cross-link-settings".
 */
export interface CrossLinkSetting {
  id: number;
  /**
   * Configure automatic tag-based matching algorithm
   */
  autoMatching: {
    /**
     * Minimum shared tags required for a match
     */
    minTagOverlap: number;
    /**
     * Minimum match score (0-1)
     */
    minScoreThreshold: number;
    /**
     * Maximum auto-matched resources per document
     */
    maxAutoMatches: number;
    /**
     * Enable automatic matching globally
     */
    enabled?: boolean | null;
  };
  /**
   * Default display settings for cross-links
   */
  displayDefaults: {
    /**
     * Default display mode for new documents
     */
    defaultDisplayMode: 'hover' | 'cards' | 'both';
    /**
     * Hover delay in milliseconds
     */
    hoverDelayMs: number;
    /**
     * Show resource cards at the end of sections
     */
    showResourceCardsAfterSection?: boolean | null;
    /**
     * Show aggregated resources at document end
     */
    showResourceCardsAtDocumentEnd?: boolean | null;
    /**
     * Maximum resource cards to show per section
     */
    maxCardsPerSection?: number | null;
  };
  /**
   * Adjust how different factors influence matching scores
   */
  scoringWeights: {
    /**
     * Tag overlap weight (0-1)
     */
    tagOverlapWeight: number;
    /**
     * Category mapping weight (0-1)
     */
    categoryMappingWeight: number;
    /**
     * Title similarity weight (0-1)
     */
    titleSimilarityWeight: number;
  };
  /**
   * Map documentation categories to resource categories for boosted matching
   */
  categoryMappings?:
    | {
        /**
         * Documentation category (e.g., "getting-started")
         */
        docCategory: string;
        /**
         * Resource categories that should be boosted
         */
        resourceCategories: (number | Category)[];
        /**
         * Boost multiplier (1.0 = normal, 2.0 = double)
         */
        boostWeight: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable or disable cross-linking features
   */
  features?: {
    /**
     * Enable hover preview cards
     */
    enableHoverCards?: boolean | null;
    /**
     * Enable inline resource cards
     */
    enableInlineCards?: boolean | null;
    /**
     * Enable section-level linking
     */
    enableSectionLinks?: boolean | null;
    /**
     * Enable code block linking
     */
    enableCodeBlockLinks?: boolean | null;
    /**
     * Show related docs on resource pages
     */
    enableBidirectionalLinks?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        tagline?: T;
        description?: T;
        version?: T;
      };
  social?:
    | T
    | {
        github?: T;
        twitter?: T;
        discord?: T;
        linkedin?: T;
      };
  footer?:
    | T
    | {
        copyrightText?: T;
        showVersion?: T;
        showBuildInfo?: T;
      };
  seo?:
    | T
    | {
        ogImage?: T;
        twitterHandle?: T;
        googleAnalyticsId?: T;
      };
  features?:
    | T
    | {
        maintenanceMode?: T;
        maintenanceMessage?: T;
        enableVoiceAssistant?: T;
        enableSearch?: T;
        enableAnalytics?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        supportUrl?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
        type?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cross-link-settings_select".
 */
export interface CrossLinkSettingsSelect<T extends boolean = true> {
  autoMatching?:
    | T
    | {
        minTagOverlap?: T;
        minScoreThreshold?: T;
        maxAutoMatches?: T;
        enabled?: T;
      };
  displayDefaults?:
    | T
    | {
        defaultDisplayMode?: T;
        hoverDelayMs?: T;
        showResourceCardsAfterSection?: T;
        showResourceCardsAtDocumentEnd?: T;
        maxCardsPerSection?: T;
      };
  scoringWeights?:
    | T
    | {
        tagOverlapWeight?: T;
        categoryMappingWeight?: T;
        titleSimilarityWeight?: T;
      };
  categoryMappings?:
    | T
    | {
        docCategory?: T;
        resourceCategories?: T;
        boostWeight?: T;
        id?: T;
      };
  features?:
    | T
    | {
        enableHoverCards?: T;
        enableInlineCards?: T;
        enableSectionLinks?: T;
        enableCodeBlockLinks?: T;
        enableBidirectionalLinks?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}