/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    subcategories: Subcategory;
    tags: Tag;
    resources: Resource;
    'difficulty-levels': DifficultyLevel;
    'programming-languages': ProgrammingLanguage;
    'edit-suggestions': EditSuggestion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'difficulty-levels': DifficultyLevelsSelect<false> | DifficultyLevelsSelect<true>;
    'programming-languages': ProgrammingLanguagesSelect<false> | ProgrammingLanguagesSelect<true>;
    'edit-suggestions': EditSuggestionsSelect<false> | EditSuggestionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * CMS users who manage content and moderate submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name for the admin panel
   */
  name: string;
  /**
   * Short biography or description
   */
  bio?: string | null;
  /**
   * User role determines access level
   */
  role: 'admin' | 'editor' | 'moderator' | 'beta_tester';
  /**
   * Inactive users cannot log in
   */
  isActive?: boolean | null;
  /**
   * Fine-grained permissions (for moderators)
   */
  permissions?: {
    /**
     * Can approve or reject user comments
     */
    canApproveComments?: boolean | null;
    /**
     * Can approve or reject edit suggestions
     */
    canApproveEdits?: boolean | null;
    /**
     * Can create, edit, and delete resources
     */
    canManageResources?: boolean | null;
    /**
     * Can view site analytics and reports
     */
    canViewAnalytics?: boolean | null;
  };
  /**
   * Last successful login
   */
  lastLoginAt?: string | null;
  /**
   * Total number of logins
   */
  loginCount?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Uploaded images and files
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility (required)
   */
  alt: string;
  /**
   * Optional caption for the image
   */
  caption?: string | null;
  /**
   * Category for organization
   */
  category?: ('avatar' | 'resource' | 'doc' | 'general') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * URL-friendly identifier (e.g., "mcp-servers")
   */
  slug: string;
  /**
   * Full display name (e.g., "MCP Servers")
   */
  name: string;
  /**
   * Abbreviated name for compact displays (e.g., "MCP")
   */
  shortName: string;
  description: string;
  /**
   * Emoji icon for the category (e.g., "🔌")
   */
  icon: string;
  color: 'violet' | 'blue' | 'cyan' | 'green' | 'yellow' | 'purple' | 'pink' | 'indigo' | 'amber' | 'rose';
  /**
   * Order for displaying categories (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subcategories belong to a parent category for hierarchical organization
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  /**
   * Display name (e.g., "Desktop Apps", "CLI Tools")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "desktop-apps")
   */
  slug: string;
  /**
   * Parent category this subcategory belongs to
   */
  category: number | Category;
  /**
   * Brief description of what resources belong here
   */
  description?: string | null;
  /**
   * Optional emoji icon for the subcategory
   */
  icon?: string | null;
  /**
   * Number of resources in this subcategory (auto-calculated)
   */
  resourceCount?: number | null;
  /**
   * Display order within the parent category (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Tag name (e.g., "typescript", "ai-agent")
   */
  name: string;
  /**
   * Optional description of what this tag represents
   */
  description?: string | null;
  /**
   * Number of resources using this tag (auto-calculated)
   */
  resourceCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * Resource title (e.g., "Claude Desktop")
   */
  title: string;
  /**
   * Brief description of the resource
   */
  description: string;
  /**
   * Primary URL for the resource
   */
  url: string;
  /**
   * Primary category for this resource
   */
  category: number | Category;
  /**
   * Subcategory within the parent category
   */
  subcategory?: (number | null) | Subcategory;
  /**
   * Tags for filtering and discovery
   */
  tags?: (number | Tag)[] | null;
  /**
   * Skill level required to use this resource
   */
  difficulty?: (number | null) | DifficultyLevel;
  status: 'official' | 'community' | 'beta' | 'deprecated' | 'archived';
  /**
   * GitHub repository information (if applicable)
   */
  github?: {
    /**
     * GitHub username or organization
     */
    owner?: string | null;
    /**
     * Repository name
     */
    repo?: string | null;
    /**
     * Star count (auto-updated or manual)
     */
    stars?: number | null;
    forks?: number | null;
    /**
     * Last commit date
     */
    lastUpdated?: string | null;
    /**
     * Primary programming language
     */
    language?: (number | null) | ProgrammingLanguage;
  };
  /**
   * Latest version (for packages, MCP servers)
   */
  version?: string | null;
  /**
   * Package namespace (e.g., "@modelcontextprotocol")
   */
  namespace?: string | null;
  /**
   * Show on homepage featured section
   */
  featured?: boolean | null;
  /**
   * Reason for featuring (shown as badge)
   */
  featuredReason?: ('editors-pick' | 'most-popular' | 'new' | 'trending' | 'essential') | null;
  /**
   * Date this resource was added to the collection
   */
  addedDate: string;
  /**
   * Last date this resource was verified as active
   */
  lastVerified: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Skill levels for classifying resource difficulty
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulty-levels".
 */
export interface DifficultyLevel {
  id: number;
  /**
   * Display name (e.g., "Beginner", "Expert")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "beginner", "expert")
   */
  slug: string;
  /**
   * What this level means (e.g., "No prior experience needed")
   */
  description?: string | null;
  /**
   * Badge color for this difficulty level
   */
  color: 'green' | 'blue' | 'yellow' | 'orange' | 'red' | 'purple' | 'gray';
  /**
   * Optional emoji icon (e.g., "🌱", "🔥")
   */
  icon?: string | null;
  /**
   * Display order (0=easiest, higher=harder)
   */
  sortOrder: number;
  /**
   * Number of resources at this level (auto-calculated)
   */
  resourceCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Programming languages used in resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programming-languages".
 */
export interface ProgrammingLanguage {
  id: number;
  /**
   * Display name (e.g., "TypeScript", "Python")
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "typescript", "python")
   */
  slug: string;
  /**
   * Alternative names that should map to this language
   */
  aliases?:
    | {
        /**
         * Alternative name (e.g., "JS" for JavaScript)
         */
        alias?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tailwind color class for badges (e.g., "blue-600", "yellow-500")
   */
  color: string;
  /**
   * Optional emoji or icon identifier
   */
  icon?: string | null;
  /**
   * Official language website URL
   */
  website?: string | null;
  /**
   * Number of resources using this language (auto-calculated)
   */
  resourceCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User-submitted edit suggestions for docs and resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edit-suggestions".
 */
export interface EditSuggestion {
  id: number;
  /**
   * Brief description of the suggested change
   */
  title: string;
  /**
   * Type of content being edited
   */
  targetType: 'doc' | 'resource';
  /**
   * ID or slug of the target content
   */
  targetId: string;
  /**
   * URL where the suggestion was made
   */
  targetUrl?: string | null;
  /**
   * The current content (for reference)
   */
  currentContent?: string | null;
  /**
   * The proposed changes (use markdown)
   */
  suggestedContent: string;
  /**
   * Why this change should be made
   */
  reason?: string | null;
  status: 'pending' | 'reviewing' | 'approved' | 'rejected' | 'merged';
  /**
   * Priority for review
   */
  priority?: ('low' | 'normal' | 'high' | 'critical') | null;
  /**
   * Information about who submitted this suggestion
   */
  submitter?: {
    type?: ('public' | 'cms' | 'anonymous') | null;
    /**
     * User ID (public or CMS)
     */
    userId?: string | null;
    /**
     * Email for notification about status
     */
    email?: string | null;
    /**
     * Display name
     */
    name?: string | null;
  };
  submitterEmail?: string | null;
  /**
   * Moderator who reviewed this
   */
  reviewedBy?: (number | null) | User;
  /**
   * Notes from the reviewer (internal)
   */
  reviewNotes?: string | null;
  /**
   * Reason for rejection (sent to submitter)
   */
  rejectionReason?: string | null;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'difficulty-levels';
        value: number | DifficultyLevel;
      } | null)
    | ({
        relationTo: 'programming-languages';
        value: number | ProgrammingLanguage;
      } | null)
    | ({
        relationTo: 'edit-suggestions';
        value: number | EditSuggestion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  role?: T;
  isActive?: T;
  permissions?:
    | T
    | {
        canApproveComments?: T;
        canApproveEdits?: T;
        canManageResources?: T;
        canViewAnalytics?: T;
      };
  lastLoginAt?: T;
  loginCount?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avatar?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortName?: T;
  description?: T;
  icon?: T;
  color?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  icon?: T;
  resourceCount?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  resourceCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  url?: T;
  category?: T;
  subcategory?: T;
  tags?: T;
  difficulty?: T;
  status?: T;
  github?:
    | T
    | {
        owner?: T;
        repo?: T;
        stars?: T;
        forks?: T;
        lastUpdated?: T;
        language?: T;
      };
  version?: T;
  namespace?: T;
  featured?: T;
  featuredReason?: T;
  addedDate?: T;
  lastVerified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulty-levels_select".
 */
export interface DifficultyLevelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  icon?: T;
  sortOrder?: T;
  resourceCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programming-languages_select".
 */
export interface ProgrammingLanguagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  color?: T;
  icon?: T;
  website?: T;
  resourceCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edit-suggestions_select".
 */
export interface EditSuggestionsSelect<T extends boolean = true> {
  title?: T;
  targetType?: T;
  targetId?: T;
  targetUrl?: T;
  currentContent?: T;
  suggestedContent?: T;
  reason?: T;
  status?: T;
  priority?: T;
  submitter?:
    | T
    | {
        type?: T;
        userId?: T;
        email?: T;
        name?: T;
      };
  submitterEmail?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  rejectionReason?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site configuration - changes apply site-wide
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  general: {
    /**
     * The name of the website
     */
    siteName: string;
    /**
     * Short tagline displayed in header and meta tags
     */
    tagline: string;
    /**
     * Used for SEO meta description and Open Graph
     */
    description: string;
    /**
     * Current version displayed in footer
     */
    version?: string | null;
  };
  social?: {
    /**
     * GitHub repository URL
     */
    github?: string | null;
    /**
     * Twitter/X profile URL (optional)
     */
    twitter?: string | null;
    /**
     * Discord server invite URL (optional)
     */
    discord?: string | null;
    /**
     * LinkedIn profile or company page URL (optional)
     */
    linkedin?: string | null;
  };
  footer?: {
    /**
     * Copyright notice in footer
     */
    copyrightText?: string | null;
    showVersion?: boolean | null;
    /**
     * Shows build date and commit SHA
     */
    showBuildInfo?: boolean | null;
  };
  seo?: {
    /**
     * Default Open Graph image for social sharing
     */
    ogImage?: string | null;
    /**
     * Twitter handle for Twitter Cards (e.g., @claudeinsider)
     */
    twitterHandle?: string | null;
    /**
     * Google Analytics measurement ID (optional)
     */
    googleAnalyticsId?: string | null;
  };
  features?: {
    /**
     * Enable to show maintenance page to visitors
     */
    maintenanceMode?: boolean | null;
    /**
     * Message displayed during maintenance
     */
    maintenanceMessage?: string | null;
    /**
     * Show/hide the AI voice assistant feature
     */
    enableVoiceAssistant?: boolean | null;
    /**
     * Enable/disable the search functionality
     */
    enableSearch?: boolean | null;
    /**
     * Enable Vercel Analytics tracking
     */
    enableAnalytics?: boolean | null;
  };
  contact?: {
    /**
     * Primary contact email address
     */
    email?: string | null;
    /**
     * URL for support/issues
     */
    supportUrl?: string | null;
  };
  announcement?: {
    enabled?: boolean | null;
    /**
     * Short message for the top banner
     */
    message?: string | null;
    /**
     * Optional link for "Learn more"
     */
    link?: string | null;
    type?: ('info' | 'success' | 'warning' | 'feature') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        tagline?: T;
        description?: T;
        version?: T;
      };
  social?:
    | T
    | {
        github?: T;
        twitter?: T;
        discord?: T;
        linkedin?: T;
      };
  footer?:
    | T
    | {
        copyrightText?: T;
        showVersion?: T;
        showBuildInfo?: T;
      };
  seo?:
    | T
    | {
        ogImage?: T;
        twitterHandle?: T;
        googleAnalyticsId?: T;
      };
  features?:
    | T
    | {
        maintenanceMode?: T;
        maintenanceMessage?: T;
        enableVoiceAssistant?: T;
        enableSearch?: T;
        enableAnalytics?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        supportUrl?: T;
      };
  announcement?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
        type?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}