import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { pool } from "@/lib/db";

export const runtime = "nodejs";

/**
 * GET /api/user/claude-md
 * Generate a personalized CLAUDE.md template for the user
 *
 * The template includes:
 * - User preferences from assistant_settings
 * - Recommended Claude Code configurations
 * - Links to Claude Insider documentation
 */
export async function GET() {
  try {
    // Get user session
    const session = await getSession();
    if (!session?.user?.id) {
      return NextResponse.json(
        { error: "Authentication required" },
        { status: 401 }
      );
    }

    // Get user's assistant settings if they exist
    let preferredModel = "claude-sonnet-4-20250514";
    let temperature = 0.7;
    let responseStyle = "balanced";

    try {
      const settingsResult = await pool.query(
        `SELECT preferred_model, temperature, response_style FROM assistant_settings WHERE user_id = $1`,
        [session.user.id]
      );
      if (settingsResult.rows[0]) {
        preferredModel = settingsResult.rows[0].preferred_model || preferredModel;
        temperature = settingsResult.rows[0].temperature ?? temperature;
        responseStyle = settingsResult.rows[0].response_style || responseStyle;
      }
    } catch {
      // Settings table might not exist yet, use defaults
    }

    // Get user info
    const userResult = await pool.query(
      `SELECT name, email FROM "user" WHERE id = $1`,
      [session.user.id]
    );
    const user = userResult.rows[0];

    const userName = user?.name || "Developer";
    const currentDate = new Date().toISOString().split("T")[0];

    // Generate CLAUDE.md content
    const content = `# CLAUDE.md - Project Guidelines

> Generated by [Claude Insider](https://www.claudeinsider.com) on ${currentDate}
> User: ${userName}

## Overview

This file provides context and guidelines for Claude Code when working on this project.

## Preferences

### Communication Style
- **Response Style**: ${responseStyle === "concise" ? "Concise and direct" : responseStyle === "detailed" ? "Detailed and thorough" : "Balanced mix of clarity and detail"}
- **Code Comments**: Include helpful inline comments for complex logic
- **Explanations**: Provide brief explanations for significant changes

### Code Quality
- Follow existing code conventions in the project
- Write clean, maintainable code
- Include error handling where appropriate
- Prefer readability over cleverness

## Project Context

<!-- Add your project-specific context here -->

### Tech Stack
<!-- List your main technologies -->
- Framework:
- Language:
- Database:
- Testing:

### Important Files
<!-- List key files Claude should know about -->
- Entry point:
- Configuration:
- Main logic:

### Conventions
<!-- List coding conventions for your project -->
- Naming:
- File structure:
- Import order:

## Commands Reference

Common commands for this project:

\`\`\`bash
# Development
# npm run dev

# Testing
# npm test

# Building
# npm run build

# Linting
# npm run lint
\`\`\`

## Claude Insider Resources

For more tips on using Claude effectively:

- [Getting Started with Claude Code](https://www.claudeinsider.com/docs/getting-started)
- [Configuration Guide](https://www.claudeinsider.com/docs/configuration)
- [Tips & Tricks](https://www.claudeinsider.com/docs/tips-and-tricks)
- [API Reference](https://www.claudeinsider.com/docs/api)

---

*This CLAUDE.md was generated with your preferences from Claude Insider. Update it to match your specific project needs.*

*Model preference: ${preferredModel}, Temperature: ${temperature}*
`;

    return NextResponse.json({
      content,
      generatedAt: new Date().toISOString(),
      preferences: {
        model: preferredModel,
        temperature,
        responseStyle,
      },
    });
  } catch (error) {
    console.error("CLAUDE.md generation error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to generate CLAUDE.md" },
      { status: 500 }
    );
  }
}
