"use client";

/**
 * MCP Export Modal Component
 *
 * Provides multiple export options for MCP configurations:
 * - Copy raw JSON
 * - Copy with Claude Desktop path instructions
 * - Copy with Claude Code path instructions
 * - Download as .json file
 */

import { useState, useCallback } from "react";
import { cn } from "@/lib/design-system";
import { useToast } from "@/components/toast";
import {
  XMarkIcon,
  ClipboardIcon,
  ArrowDownTrayIcon,
  ComputerDesktopIcon,
  CommandLineIcon,
  CheckIcon,
  DocumentTextIcon,
} from "@heroicons/react/24/outline";

interface MCPExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  config: string;
  serverCount: number;
}

type ExportFormat = "json" | "claude-desktop" | "claude-code" | "download";

const EXPORT_OPTIONS: Array<{
  id: ExportFormat;
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  action: "copy" | "download";
}> = [
  {
    id: "json",
    name: "Copy JSON",
    description: "Copy the raw configuration to clipboard",
    icon: ClipboardIcon,
    action: "copy",
  },
  {
    id: "claude-desktop",
    name: "Claude Desktop",
    description: "Copy with file path instructions for Claude Desktop",
    icon: ComputerDesktopIcon,
    action: "copy",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    description: "Copy with setup instructions for Claude Code CLI",
    icon: CommandLineIcon,
    action: "copy",
  },
  {
    id: "download",
    name: "Download File",
    description: "Download as mcp-config.json file",
    icon: ArrowDownTrayIcon,
    action: "download",
  },
];

// Platform-specific paths for Claude Desktop
const CLAUDE_DESKTOP_PATHS = {
  macos: "~/Library/Application Support/Claude/claude_desktop_config.json",
  windows: "%APPDATA%\\Claude\\claude_desktop_config.json",
  linux: "~/.config/Claude/claude_desktop_config.json",
};

export function MCPExportModal({
  isOpen,
  onClose,
  config,
  serverCount,
}: MCPExportModalProps) {
  const { success, error } = useToast();
  const [copiedFormat, setCopiedFormat] = useState<ExportFormat | null>(null);

  // Generate export content based on format
  const getExportContent = useCallback(
    (format: ExportFormat): string => {
      switch (format) {
        case "json":
          return config;

        case "claude-desktop":
          return `# Claude Desktop MCP Configuration

## Step 1: Locate your settings file

**macOS:**
\`\`\`
${CLAUDE_DESKTOP_PATHS.macos}
\`\`\`

**Windows:**
\`\`\`
${CLAUDE_DESKTOP_PATHS.windows}
\`\`\`

**Linux:**
\`\`\`
${CLAUDE_DESKTOP_PATHS.linux}
\`\`\`

## Step 2: Add this configuration

Open the file and add or merge the following into your existing config:

\`\`\`json
${config}
\`\`\`

## Step 3: Restart Claude Desktop

Close and reopen Claude Desktop for changes to take effect.

---
Generated by Claude Insider MCP Playground
https://www.claudeinsider.com/mcp-playground`;

        case "claude-code":
          return `# Claude Code MCP Configuration

## Option 1: Project-level config (recommended)

Create a \`.claude/settings.json\` file in your project root:

\`\`\`bash
mkdir -p .claude
cat > .claude/settings.json << 'EOF'
${config}
EOF
\`\`\`

## Option 2: Global config

Add to your global Claude Code settings:

**macOS/Linux:**
\`\`\`bash
# Edit ~/.claude/settings.json
\`\`\`

**Windows:**
\`\`\`powershell
# Edit %USERPROFILE%\\.claude\\settings.json
\`\`\`

## Step 2: Verify servers are loaded

Run \`claude\` and check for MCP server initialization messages.

---
Generated by Claude Insider MCP Playground
https://www.claudeinsider.com/mcp-playground`;

        default:
          return config;
      }
    },
    [config]
  );

  // Handle copy action
  const handleCopy = useCallback(
    async (format: ExportFormat) => {
      try {
        const content = getExportContent(format);
        await navigator.clipboard.writeText(content);
        setCopiedFormat(format);
        success(
          "Copied!",
          format === "json"
            ? "Configuration copied to clipboard"
            : "Instructions copied to clipboard"
        );
        setTimeout(() => setCopiedFormat(null), 2000);
      } catch {
        error("Failed to copy", "Please try again");
      }
    },
    [getExportContent, success, error]
  );

  // Handle download action
  const handleDownload = useCallback(() => {
    try {
      const blob = new Blob([config], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = "mcp-config.json";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      success("Downloaded!", "mcp-config.json saved");
    } catch {
      error("Download failed", "Please try again");
    }
  }, [config, success, error]);

  // Handle export action
  const handleExport = useCallback(
    (option: (typeof EXPORT_OPTIONS)[0]) => {
      if (option.action === "copy") {
        handleCopy(option.id);
      } else {
        handleDownload();
      }
    },
    [handleCopy, handleDownload]
  );

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative w-full max-w-lg overflow-hidden ui-bg-modal rounded-2xl shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b ui-border">
          <div>
            <h2 className="text-lg font-semibold ui-text-heading">
              Export Configuration
            </h2>
            <p className="text-sm ui-text-secondary mt-0.5">
              {serverCount} server{serverCount !== 1 ? "s" : ""} configured
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg ui-btn-ghost"
            aria-label="Close"
          >
            <XMarkIcon className="h-5 w-5" />
          </button>
        </div>

        {/* Export options */}
        <div className="p-4 space-y-3">
          {EXPORT_OPTIONS.map((option) => {
            const Icon = option.icon;
            const isCopied = copiedFormat === option.id;

            return (
              <button
                key={option.id}
                onClick={() => handleExport(option)}
                className={cn(
                  "w-full flex items-center gap-4 p-4 rounded-xl text-left",
                  "ui-bg-card border ui-border",
                  "hover:border-blue-500/50 hover:shadow-lg transition-all",
                  "focus:outline-none focus:ring-2 focus:ring-blue-500"
                )}
              >
                <div
                  className={cn(
                    "p-3 rounded-xl shrink-0",
                    isCopied
                      ? "bg-emerald-500/10"
                      : "bg-gradient-to-br from-violet-500/10 to-cyan-500/10"
                  )}
                >
                  {isCopied ? (
                    <CheckIcon className="h-6 w-6 text-emerald-500" />
                  ) : (
                    <Icon className="h-6 w-6 text-violet-600 dark:text-violet-400" />
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-medium ui-text-heading">{option.name}</p>
                  <p className="text-sm ui-text-secondary mt-0.5">
                    {option.description}
                  </p>
                </div>
                {option.action === "copy" && (
                  <ClipboardIcon className="h-5 w-5 ui-text-secondary shrink-0" />
                )}
                {option.action === "download" && (
                  <ArrowDownTrayIcon className="h-5 w-5 ui-text-secondary shrink-0" />
                )}
              </button>
            );
          })}
        </div>

        {/* Preview section */}
        <div className="px-4 pb-4">
          <div className="p-3 rounded-xl bg-gray-100 dark:bg-gray-800/50">
            <div className="flex items-center gap-2 mb-2">
              <DocumentTextIcon className="h-4 w-4 ui-text-secondary" />
              <span className="text-xs font-medium ui-text-secondary">
                Configuration Preview
              </span>
            </div>
            <pre className="text-xs font-mono ui-text-body overflow-x-auto max-h-32">
              {config.slice(0, 300)}
              {config.length > 300 && "..."}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
