"use client";

/**
 * Profile Basics Step
 *
 * Step 1: Collect display name, username, bio, and avatar.
 * This is a required step (not skippable).
 *
 * Requirements:
 * - Display name: Required, 2-50 characters
 * - Username: Required, lowercase, no spaces, 3-30 characters, unique
 */

import { useState, useEffect, useCallback } from "react";
import { cn } from "@/lib/design-system";
import { useWizard } from "../wizard-context";
import { WizardNavigation } from "../wizard-navigation";
import { StepWrapper } from "../shared/step-wrapper";
import { AvatarUpload } from "../shared/avatar-upload";

/**
 * Generate a valid username from display name
 * - Lowercase
 * - No spaces
 * - Only alphanumeric and underscores
 */
function generateUsername(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "") // Remove spaces
    .replace(/[^a-z0-9_]/g, "") // Remove special chars except underscore
    .slice(0, 30); // Max 30 chars
}

/**
 * Validate username format
 */
function validateUsernameFormat(username: string): string | null {
  if (!username) {
    return "Username is required";
  }
  if (username.length < 3) {
    return "Username must be at least 3 characters";
  }
  if (username.length > 30) {
    return "Username must be less than 30 characters";
  }
  if (!/^[a-z0-9_]+$/.test(username)) {
    return "Username can only contain lowercase letters, numbers, and underscores";
  }
  if (/^\d/.test(username)) {
    return "Username cannot start with a number";
  }
  return null;
}

export function ProfileBasicsStep() {
  const { data, updateData, setError } = useWizard();
  const [usernameStatus, setUsernameStatus] = useState<"idle" | "checking" | "available" | "taken">("idle");
  const [usernameError, setUsernameError] = useState<string | null>(null);

  // Check username availability
  const checkUsername = useCallback(async (username: string) => {
    const formatError = validateUsernameFormat(username);
    if (formatError) {
      setUsernameError(formatError);
      setUsernameStatus("idle");
      return;
    }

    setUsernameStatus("checking");
    setUsernameError(null);

    try {
      const response = await fetch(`/api/user/check-username?username=${encodeURIComponent(username)}`);
      const result = await response.json();

      if (result.available) {
        setUsernameStatus("available");
        setUsernameError(null);
      } else {
        setUsernameStatus("taken");
        setUsernameError("This username is already taken");
      }
    } catch {
      setUsernameStatus("idle");
      setUsernameError("Failed to check username availability");
    }
  }, []);

  // Debounce username check
  useEffect(() => {
    if (!data.username) {
      setUsernameStatus("idle");
      setUsernameError(null);
      return;
    }

    const timer = setTimeout(() => {
      checkUsername(data.username);
    }, 500);

    return () => clearTimeout(timer);
  }, [data.username, checkUsername]);

  // Auto-generate username when display name changes (only if username is empty or matches previous suggestion)
  const handleDisplayNameChange = (newName: string) => {
    const oldSuggestion = generateUsername(data.displayName);
    const isUsernameAutoGenerated = !data.username || data.username === oldSuggestion;

    updateData({ displayName: newName });

    // Auto-update username if it was auto-generated
    if (isUsernameAutoGenerated) {
      const newSuggestion = generateUsername(newName);
      updateData({ username: newSuggestion });
    }
  };

  // Handle username input - enforce lowercase, no spaces
  const handleUsernameChange = (value: string) => {
    const cleaned = value
      .toLowerCase()
      .replace(/\s+/g, "")
      .replace(/[^a-z0-9_]/g, "")
      .slice(0, 30);
    updateData({ username: cleaned });
  };

  const handleNext = async (): Promise<boolean> => {
    // Validate display name
    const trimmedName = data.displayName.trim();
    if (!trimmedName) {
      setError("Display name is required");
      return false;
    }

    if (trimmedName.length < 2) {
      setError("Display name must be at least 2 characters");
      return false;
    }

    if (trimmedName.length > 50) {
      setError("Display name must be less than 50 characters");
      return false;
    }

    // Validate username
    const formatError = validateUsernameFormat(data.username);
    if (formatError) {
      setError(formatError);
      return false;
    }

    if (usernameStatus === "taken") {
      setError("Please choose a different username");
      return false;
    }

    if (usernameStatus === "checking") {
      setError("Please wait while we check username availability");
      return false;
    }

    // Upload avatar if one was selected
    if (data.avatarFile) {
      try {
        const formData = new FormData();
        formData.append("avatar", data.avatarFile);

        const response = await fetch("/api/user/avatar", {
          method: "POST",
          body: formData,
        });

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.error || "Failed to upload avatar");
        }

        const result = await response.json();

        // Update preview with the permanent URL
        updateData({ avatarPreview: result.url });
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to upload avatar");
        return false;
      }
    }

    // Save profile basics including username
    try {
      const response = await fetch("/api/user/update-profile", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          displayName: trimmedName,
          username: data.username,
          bio: data.bio.trim() || undefined,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to save profile");
      }

      return true;
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save profile");
      return false;
    }
  };

  return (
    <StepWrapper>
      <div className="space-y-5">
        {/* Avatar upload */}
        <AvatarUpload />

        {/* Display name */}
        <div>
          <label
            htmlFor="displayName"
            className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
          >
            Display Name <span className="text-red-500">*</span>
          </label>
          <input
            id="displayName"
            type="text"
            value={data.displayName}
            onChange={(e) => handleDisplayNameChange(e.target.value)}
            maxLength={50}
            className={cn(
              "w-full px-4 py-2.5 rounded-lg",
              "bg-white dark:bg-gray-900",
              "border border-gray-200 dark:border-gray-700",
              "text-gray-900 dark:text-white",
              "placeholder-gray-400 dark:placeholder-gray-500",
              "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
              "transition-colors duration-200"
            )}
            placeholder="How should we call you?"
          />
          <p className="text-xs text-gray-400 mt-1 text-right">
            {data.displayName.length}/50
          </p>
        </div>

        {/* Username */}
        <div>
          <label
            htmlFor="username"
            className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
          >
            Username <span className="text-red-500">*</span>
          </label>
          <div className="relative">
            <span className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400">@</span>
            <input
              id="username"
              type="text"
              value={data.username}
              onChange={(e) => handleUsernameChange(e.target.value)}
              maxLength={30}
              className={cn(
                "w-full pl-8 pr-10 py-2.5 rounded-lg",
                "bg-white dark:bg-gray-900",
                "border",
                usernameError
                  ? "border-red-500 dark:border-red-500"
                  : usernameStatus === "available"
                  ? "border-green-500 dark:border-green-500"
                  : "border-gray-200 dark:border-gray-700",
                "text-gray-900 dark:text-white",
                "placeholder-gray-400 dark:placeholder-gray-500",
                "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
                "transition-colors duration-200"
              )}
              placeholder="your_username"
            />
            {/* Status indicator */}
            <div className="absolute right-3 top-1/2 -translate-y-1/2">
              {usernameStatus === "checking" && (
                <svg className="w-5 h-5 animate-spin text-blue-500" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
              )}
              {usernameStatus === "available" && (
                <svg className="w-5 h-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              )}
              {usernameStatus === "taken" && (
                <svg className="w-5 h-5 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              )}
            </div>
          </div>
          <div className="flex justify-between mt-1">
            <p className={cn(
              "text-xs",
              usernameError ? "text-red-500" : "text-gray-400"
            )}>
              {usernameError || "Lowercase letters, numbers, and underscores only"}
            </p>
            <p className="text-xs text-gray-400">
              {data.username.length}/30
            </p>
          </div>
        </div>

        {/* Bio */}
        <div>
          <label
            htmlFor="bio"
            className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
          >
            Bio <span className="text-gray-400 font-normal">(optional)</span>
          </label>
          <textarea
            id="bio"
            value={data.bio}
            onChange={(e) => updateData({ bio: e.target.value })}
            rows={2}
            maxLength={160}
            className={cn(
              "w-full px-4 py-2.5 rounded-lg resize-none",
              "bg-white dark:bg-gray-900",
              "border border-gray-200 dark:border-gray-700",
              "text-gray-900 dark:text-white",
              "placeholder-gray-400 dark:placeholder-gray-500",
              "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
              "transition-colors duration-200"
            )}
            placeholder="Tell us a bit about yourself..."
          />
          <p className="text-xs text-gray-400 mt-1 text-right">
            {data.bio.length}/160
          </p>
        </div>
      </div>

      <WizardNavigation onNext={handleNext} />
    </StepWrapper>
  );
}
